name: Mirror to school repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Epitech repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechMscProPromo2027/T-SEC-901-PAR-9-1-virology-12.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
